version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  target-branch: vue/threejs/main
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: vuetify
    versions:
    - 2.4.11
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: three
    versions:
    - 0.125.2
    - 0.126.0
    - 0.126.1
    - 0.127.0
    - 0.128.0
  - dependency-name: electron
    versions:
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.5
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.11.0
    - 3.9.0
    - 3.9.1
  - dependency-name: vue-i18n
    versions:
    - 8.23.0
    - 8.24.1
    - 8.24.2
    - 8.24.3
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.3.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
    - 1.7.2
  - dependency-name: sass-loader
    versions:
    - 11.0.0
  - dependency-name: vuex
    versions:
    - 3.6.2
  - dependency-name: vue-router
    versions:
    - 3.5.1
