name: 'dev'

on:
  push:
    paths:
      - '.github/workflows/dev.yml'
      - '.github/actions/godot/godot.dockerfile'
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Generate image name
        id: generate
        run: |
          REPO='${{ github.repository }}'
          echo "::set-output name=image::ghcr.io/${REPO,,}/godot/export"

      - name: Build image
        run: docker build -t '${{ steps.generate.outputs.image }}' - < .github/actions/godot/godot.dockerfile

      - name: Publish image
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: pyTooling/Actions/with-post-step@r0
        with:
          main: |
            echo '${{ github.token }}' | docker login ghcr.io -u gha --password-stdin
            docker images
            docker push '${{ steps.generate.outputs.image }}'
          post: docker logout ghcr.io
