name: 'dev'

on:
  push:
    paths:
      - 'dev.sh'
      - '.github/workflows/dev.yml'
  schedule:
    - cron: '0 0 * * 3,6'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  images:
    if: github.ref == 'refs/heads/vue/threejs/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./dev.sh -b dev
    - run: ./dev.sh -b run
    - run: ./dev.sh -p
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
