name: 'doc'

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/doc.yml'
      - '.github/publish.sh'
      - 'doc/**'
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

jobs:

  asciidoc:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build site
      run: make -C doc

    - name: Publish site to gh-pages (doc)
      if: github.event_name != 'pull_request'
      run: GITHUB_SHA="${{ github.sha }}" ./.github/publish.sh doc
