name: 'doc'

on: [push, pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: pip3 install -r docs/requirements.txt
    - name: build doc
      run: |
        cd docs
        make html
