name: 'push'

on: [push, pull_request]

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  linux:
#    strategy:
#      fail-fast: false
#      max-parallel: 3
#      matrix:
#        task: [
#          { os: ubuntu,  arg: lin },
#          { os: windows, arg: win },
#          { os: macos,   arg: osx },
#        ]
#    runs-on: ${{ matrix.task.os }}-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn electron:build -p never
#      env:
#        DIST_TARGET: ${{ matrix.task.arg }}
    # FIXME artifacts should be uploaded at once (not supported by GHA yet):
    # dist/*.zip
    # dist/*.AppImage
    # dist/*.exe
    # dist/*.dmg
#    - name: Prepare artifacts
#      shell: bash
#      run: |
#        mkdir dist/${{ matrix.task.arg }}64 dist/${{ matrix.task.arg }}32
#        mv dist/*${{ matrix.task.larg }}64.zip dist/${{ matrix.task.arg }}64/
#        mv dist/*${{ matrix.task.larg }}32.zip dist/${{ matrix.task.arg }}32/
#    - uses: actions/upload-artifact@master
#      with:
#        name: ${{ matrix.task.arg }}64
#        path: dist/${{ matrix.task.arg }}64
#    - uses: actions/upload-artifact@master
#      with:
#        name: ${{ matrix.task.arg }}32
#        path: dist/${{ matrix.task.arg }}32
