name: 'push'

on: [push, pull_request]

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    #- run: sudo dpkg --add-architecture i386
    - run: sudo apt-get update -qq
    # TODO win
    #- run: sudo apt-get install -y wine-stable nsis
    - run: yarn
    - run: DIST_TARGET=linux64 yarn dist
    # TODO win
    # - run: xvfb-run --auto-servernum --server-args="-screen 0, ${RESOLUTION:-1600x900}x24" yarn dist
    - uses: actions/upload-artifact@master
      with:
        name: lin and win
        # FIXME should be (not supported by GHA yet):
        # dist/*.zip
        # dist/*.exe
        # dist/*.AppImage
        path: dist

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - run: yarn
    - run: yarn dist
    - uses: actions/upload-artifact@master
      with:
        name: osx
        # FIXME should be (not supported by GHA yet):
        # dist/*.dmg
        path: dist
