name: 'push'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn build
    - run: cp -vr hwstudio dist
    - uses: actions/upload-artifact@v2
      with:
        name: hwstudio
        path: dist
    - name: build for GHP
      run: |
        rm -rf dist
        yarn build
      env:
        BASE_URL: '/hwstudio/vue-three'
    - name: 'publish site to gh-pages'
      if: github.event_name != 'pull_request' && github.repository == 'umarcor/hwstudio'
      env:
        GH_DEPKEY: ${{ secrets.GHA_DEPLOY_KEY }}
      run: |
        mkdir pages
        cd pages
        git init
        cp ../.git/config ./.git/config
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git fetch
        git checkout -b gh-pages origin/gh-pages
        if [ ! -f .nojekyll ]; then
          touch .nojekyll
        fi
        if [ -d vue-three ]; then
          git rm -rf vue-three
        fi
        git commit -am "clean vue-three ${{ github.sha }}"
        mv ../dist vue-three
        git add vue-three/*
        git commit -am "update vue-three ${{ github.sha }}"
        git push -u origin +gh-pages
        cd ..
        rm -rf pages

  lin:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn electron:build --publish never
    - uses: actions/upload-artifact@v2
      with:
        name: hwstudio_lin
        path: dist_electron/linux-unpacked

  win:
    needs: [test]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn electron:build --publish never
    - uses: actions/upload-artifact@v2
      with:
        name: hwstudio_win
        path: dist_electron/win-unpacked
