name: 'push'

on:
  push:
  pull_request:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn build
    - name: 'publish site to gh-pages'
      if: github.event_name != 'pull_request' && github.repository == 'umarcor/hwstudio'
      env:
        GH_DEPKEY: ${{ secrets.GHA_DEPLOY_KEY }}
      run: |
        cd dist/
        touch .nojekyll
        git init
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -a -m "update ${{ github.sha }}"
        git remote add origin "git@github.com:${{ github.repository }}"
        eval `ssh-agent -t 60 -s`
        echo "$GH_DEPKEY" | ssh-add -
        mkdir -p ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git push -u origin +HEAD:gh-pages
        ssh-agent -k
    - run: yarn electron:build --publish never
    - uses: actions/upload-artifact@master
      with:
        name: 3Dhwstudio
        path: dist_electron
